### PR TITLE
Make ComPADRE import and generic questions optional and tidy up analytics setting

### PR DESCRIPTION
**Pull request by pauln**
Make the ComPADRE import function and generic question creation optional at the site level via new config options, and convert the analytics setting to plugin config (from site config).

### CODE REVIEW

**Comment by wjunkin** [comment]
Paul, I will have to think about this some more. I am working on a learner analytics project with Bob Puffer (puffro01@luther.edu) and many others and some college deans and administrators may want to be able to use analytics to increase retention by an early identification of students who may be at risk of dropping out of school. Thus, they may want to be able to pull ipal response data from all the courses a student is taking. So, it might be good to allow Moodle administrators to be able to override the analytics choices that individual professors select. 
     Regarding Compadre questions: Almost all teachers teaching introductory physics courses use these question, but this is useless for all other courses (well, maybe useful for a few math courses as well). I hope that questions from other disciplines will be added to the Compadre database. So, it seems to me making this an option in individual courses or individual ipal instances may make more sense than making this a site-wide setting.
     Regarding the creation of generic questions: Making this site-wide optional certainly makes sense to me. I like the generic questions and this informs that teacher that the text of a question can be in some other document or be given verbally. So, I am in favor of this setting but I want to develop good, informative text to allow the Moodle administrators (many of whom have little teaching experience and may not know about the power of in-class polling) to make an informed decision. Leaving out the generic questions cleans up the question bank.
     Again, thanks for your input.

**Comment by pauln** [comment]
I wonder if I wasn't clear enough about the level of the config options - all three settings (the existing analytics option, plus the two new ones to toggle ComPADRE import and generic questions) are at the site level; they're all (with the commits proposed here) now plugin configuration settings rather than site configuration settings - they get stored in mdl_config_plugins rather than mdl_config, and never end up being available in the $CFG global.

The analytics setting doesn't actually do anything at present - you've got it there, but it's not used; the data is being sent by the cron job no matter what this option is set to.  All I've done is migrate it from site config to plugin config, as above.  It would be good to make the cron job actually obey the setting, though, as I'm sure some institutions will look unfavourably upon the idea of sending data to an external party; I've pushed [a commit to another branch](https://github.com/pauln/moodle-mod_ipal/compare/config...pauln:analytics) which does this (it's based on the branch from this pull request, so you'd need to adjust the get_config call if you don't pull in the anaytics config migration commit from this PR).

As for ComPADRE questions, I would expect that some institutions will want to disabled this option entirely, which is what the setting I've added currently does.  If desired, it'd certainly be possible to add an instance-level setting (course-level might be trickier) to toggle it, which is only shown (and only makes any difference) if the site-level setting is enabled.

The generic questions could certainly do with a better explanation, but I tried to give a brief explanation of what the option does - though I did have a bit of trouble trying to figure out how to word it.  If you can come up with a clearer way to say it, by all means change it - I'm not at all attached to the description I've put in; it's just there because some kind of explanation was required.

**Comment by wjunkin** [comment]
Thanks, Paul, for clearing up the functioning of your modifications of the code. I did not try out the code, so I didn't know what it did. Also, I thought the setting to not send information to ComPADRE really did what I thought it did. You are correct that some schools will not want data sent to ComPADRE, even though almost all the data is turned into hashes so that only the school from which the data came can identify the professor, the course, or the student. Obviously I didn't make the settings do what I thought they should do. Thanks for straightening that out. Now that I have merged these changes I'll examine the code more closely and see what the explanations now state. Again, thanks for your help.

**Comment by pauln** [comment]
You're welcome; IPAL is a great idea, and I'm keen to see it realise its full potential.

**Comment by wjunkin** [comment]
I think that (eventually) it would be best if ipal and quiz were combined so that ipal was an option in quiz. Advantages for quiz: 1) Teachers would have an interface to see in real time how students were responding to quiz questions, both with the histogram (one question) and the spreadsheet (all the questions) view. 2) Students could use Apps on smart phones to respond to questions. Advantages to ipal: 1) It would make it easier to maintain ipal, since changes to Moodle (such as the question bank interface or the storing of the question list in the slots table) would not require separate upgrading in the ipal code once the quiz code were changed. Disadvantage to quiz: 1) There would be another option in the quiz menu and more options sometimes confuse teachers. Changes that might be required: 1) Some ipal features, such as sending polling data to CompADRE, would probably be eliminated, but future learner analytics programs may not need this feature anyhow. 
If you wish to add your thoughts on this, I will value your opinion.

**Comment by wjunkin** [comment]
Hi, Paul,
When I have checked more thoroughly everything seems to be working without a problem. I will investigate more completely and see what caused the original problem. Sorry for the false alarm.

**Pull request merged**
